#!/bin/bash

# bootstrap installs development tools, chat tools, and preferences, like
# plugins or fonts.

# Install tools
sudo dnf -y module install nodejs:14
sudo dnf -y copr enable luminoso/Signal-Desktop
sudo dnf -y install alacritty tmux zsh signal-desktop gh util-linux-user gnome-tweaks htop i3 gnome-shell-extension-pop-shell xprop gnome-shell-extension

# Stack obfuscates their download URL for their linux client. Install from
# https://slack.com/downloads/linux

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install GVM and dependencies
sudo dnf -y install bison
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

# Install neovim from upstream since it's more up-to-date than what's available
# from package repositories.
if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir -p "$HOME/.local/bin"
fi
# This will always update nvim
curl --output-dir "$HOME/Downloads/" -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
cp "$HOME/Downloads/nvim.appimage" "$HOME/.local/bin/nvim"
chmod +x "$HOME/.local/bin/nvim"
rm "$HOME/Downloads/nvim.appimage"

# Install tmux plugin manager if needed
if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# Install Hack Nerd Font - which contain glyphs used in various neovim and tmux
# plugins. Make sure we have a directory for custom fonts
if [[ ! -d "$HOME/.local/share/fonts" ]]; then
        mkdir -p ~/.local/share/fonts
        wget -O /tmp/Hack.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        unzip -d ~/.local/share/fonts -o /tmp/Hack.zip
        rm /tmp/Hack.zip
fi

## Configure extensions
# firefox https://extensions.gnome.org/local/
