#!/bin/bash

# bootstrap installs development tools, chat tools, and preferences, like
# plugins or fonts.

# Setup docker repository
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

# Install tools
sudo dnf -y module install nodejs:14

# Install golang from packages, otherwise we'll hit a bootstrap problem
# compiling later versions of golang. See
# https://github.com/moovweb/gvm#a-note-on-compiling-go-15
sudo dnf -y install alacritty tmux tmate zsh gh util-linux-user gnome-tweaks htop i3 gnome-shell-extension-pop-shell xprop golang python-pip skopeo ffmpeg-free ffmpeg-free-devel gcc-c++ docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.signal.Signal

# Install network utlities for VPNs and kerberos client
sudo dnf install -y NetworkManager-openvpn NetworkManager-openvpn-gnome krb5-workstation

# Stack obfuscates their download URL for their linux client. Install from
# https://slack.com/downloads/linux

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


# Setup ~/.zsh directory for git completion scripts.
if [[ ! -d "$HOME/.zsh" ]]; then
        mkdir -p "$HOME/.zsh"
fi

# Install GVM and dependencies
sudo dnf -y install bison
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

# Install neovim from upstream since it's more up-to-date than what's available
# from package repositories.
if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir -p "$HOME/.local/bin"
fi
# This will always update nvim
curl --output-dir "$HOME/Downloads/" -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
cp "$HOME/Downloads/nvim.appimage" "$HOME/.local/bin/nvim"
chmod +x "$HOME/.local/bin/nvim"
rm "$HOME/Downloads/nvim.appimage"

# Install tmux plugin manager if needed
if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# Install Hack Nerd Font - which contain glyphs used in various neovim and tmux
# plugins. Make sure we have a directory for custom fonts
if [[ ! -d "$HOME/.local/share/fonts" ]]; then
        mkdir -p ~/.local/share/fonts
        wget -O /tmp/Hack.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        unzip -d ~/.local/share/fonts -o /tmp/Hack.zip
        rm /tmp/Hack.zip
fi
